import {
  siReact,
  siTypescript,
  siPython,
  siOpenjdk,
  siNodedotjs,
  siExpress,
  siFlask,
  siSupabase,
  siPostgresql,
  siVuedotjs,
  siTailwindcss,
  siFramer,
  siZod,
  siReacthookform,
  siVite,
  siDocker,
  siGithubactions,
  siSentry,
  siVitest,
} from 'simple-icons'

export const STACK_ICONS: Record<string, { svg: string; hex: string }> = {
  // aliases for project tags
  'React 19': siReact,
  'Tailwind 4': siTailwindcss,
  'React': siReact,
  'TypeScript': siTypescript,
  'Python': siPython,
  'Java': siOpenjdk,
  'Node.js': siNodedotjs,
  'Express': siExpress,
  'Flask': siFlask,
  'Supabase': siSupabase,
  'PostgreSQL': siPostgresql,
  'Vue.js': siVuedotjs,
  'Tailwind CSS': siTailwindcss,
  'Framer Motion': siFramer,
  'Zod': siZod,
  'react-hook-form': siReacthookform,
  'Vite': siVite,
  'Docker': siDocker,
  'GitHub Actions': siGithubactions,
  'Sentry': siSentry,
  'Vitest': siVitest,
}

export const CATEGORY_COLORS: Record<string, string> = {
  Frontend:  '#38BDF8',
  Language:  '#34D399',
  Backend:   '#FB923C',
  Database:  '#818CF8',
  State:     '#F472B6',
  Tooling:   '#FACC15',
  DevOps:    '#F87171',
  Testing:   '#A78BFA',
}
